### PR TITLE
Theo/Documentation

### PR DESCRIPTION
**Pull request by Theo-Reignier**
### Purpose
Nodes documentation within Node-RED.
If you find a way to restrict the Imgur image size it would be great, otherwise it's fine as it is I think.

Documentation remaining for (would appreciate some help if possible):

- Initialisation nodes
- 'Measure' node
- 'TOFFOLI' gate
- 'Output nodes

Screenshot 2021-08-03 at 22 36 02

### Changes

- Adopted Node-RED conventions for nodes 'help' section.
- Developed & improved documentation for most quantum gates.
- Wrote a `Details` section that is a very simple introduction to quantum computing (qubits, block sphere & measurement)
- Included hyperlinks to the Qiskit textbook and Qiskit documentation for references

### New Requirements
When writing documentation for your nodes, please copy-paste the documentation from a similar node that was already written to adopt the same conventions. 

Please keep the `Details` section on all nodes.

At the top of each 'help' section please start with:

```
<p>
 Very short node introduction (1-2 sentence).
</p>
<p>
  Further details on how to use the node if required (such as node properties).
  <br /><br />
  In terms of the <b>Bloch Sphere</b> (see 'Details' below),   --> For quantum gates, explain what the gate does with respect 
  to the Bloch Sphere
</p>
```

### CODE REVIEW

**Comment by louislefevre** [comment]
Perhaps not in this PR but for the future, it might be beneficial to have the documentation in separate files. I haven't tried this myself but I've seen other node libraries do it. This has a few benefits:
- Separates the documentation from the nodes logic.
- Makes it easier to use the documentation for each node elsewhere (e.g. for the website idea we discussed).
- Allows us to provide documentation in multiple languages if we wish.

To give an example from the Node-RED dashboard:
- Standard HTML file for [`ui_audio.html`](https://github.com/node-red/node-red-dashboard/blob/master/nodes/ui_audio.html)
- Documentation HTML file for [`ui_audio.html`](https://github.com/node-red/node-red-dashboard/blob/master/nodes/locales/en-US/ui_audio.html)

From what I've seen, documentation files are usually stored in a `locales` folder, which contains more folders for each language ([example](https://github.com/node-red/node-red-dashboard/tree/master/nodes/locales)).

I'm happy to merge this PR as-is, but yeah just thought I'd mention this as a consideration for a future PR.

**Comment by louislefevre** [comment]
There are some nodes which display too much information on-hover ([example](https://i.imgur.com/fYx3hwg.png)):
- Quantum circuit node
- Classical register
- Qubit
- Toffoli gate
- Measure

Some other nodes also have a line break between their sentences on-hover. I think it would be cleaner (and consistent with other nodes) if there was no break ([example](https://i.imgur.com/hwRug3o.png)):
- Swap
- Identity gate
- Unitary gate
- Hadamard
- Cnot gate

**Comment by Theo-Reignier** [comment]
> Perhaps not in this PR but for the future, it might be beneficial to have the documentation in separate files. I haven't tried this myself but I've seen other node libraries do it. This has a few benefits:
> 
> * Separates the documentation from the nodes logic.
> * Makes it easier to use the documentation elsewhere (e.g. for the website idea we discussed).
> * Allows us to provide documentation in multiple languages if we wish.
> 
> To give an example from the Node-RED dashboard:
> 
> * Standard HTML file for [`ui_audio.html`](https://github.com/node-red/node-red-dashboard/blob/master/nodes/ui_audio.html)
> * Documentation HTML file for [`ui_audio.html`](https://github.com/node-red/node-red-dashboard/blob/master/nodes/locales/en-US/ui_audio.html)
> 
> From what I've seen, documentation files are usually stored in a `locales` folder, which contains more folders for each language ([example](https://github.com/node-red/node-red-dashboard/tree/master/nodes/locales)).
> 
> I'm happy to merge this PR as-is, but yeah just thought I'd mention this as a consideration for a future PR.

Thanks for the feedback, will consider that in the next documentation PR.

**Comment by Theo-Reignier** [comment]
> There are some nodes which display too much information on-hover ([example](https://i.imgur.com/fYx3hwg.png)):
> 
> * Quantum circuit node
> * Classical register
> * Qubit
> * Toffoli gate
> * Measure
> 
> Some other nodes also have a line break between their sentences on-hover. I think it would be cleaner (and consistent with other nodes) if there was no break ([example](https://i.imgur.com/hwRug3o.png)):
> 
> * Swap
> * Identity gate
> * Unitary gate
> * Hadamard
> * Cnot gate

Regarding the nodes that display too much information, you are referring to the nodes for which I did not cover the documentation yet. 

Happy to remove the line break in the hover effect !

**Comment by louislefevre** [comment]
> Regarding the nodes that display too much information, you are referring to the nodes for which I did not cover the documentation yet.

Ah okay, wasn't sure if you wanted to revise the formatting for every node in this PR but leave the actual content till later, or leave both until later.

**Review by louislefevre — APPROVED** [review]

**Comment by Theo-Reignier** [comment]
> Perhaps not in this PR but for the future, it might be beneficial to have the documentation in separate files. I haven't tried this myself but I've seen other node libraries do it. This has a few benefits:
> - Separates the documentation from the nodes logic.
> - Makes it easier to use the documentation elsewhere (e.g. for the website idea we discussed).
> - Allows us to provide documentation in multiple languages if we wish.
> 
> To give an example from the Node-RED dashboard:
> - Standard HTML file for [`ui_audio.html`](https://github.com/node-red/node-red-dashboard/blob/master/nodes/ui_audio.html)
> - Documentation HTML file for [`ui_audio.html`](https://github.com/node-red/node-red-dashboard/blob/master/nodes/locales/en-US/ui_audio.html)
> 
> From what I've seen, documentation files are usually stored in a `locales` folder, which contains more folders for each language ([example](https://github.com/node-red/node-red-dashboard/tree/master/nodes/locales)).
> 
> I'm happy to merge this PR as-is, but yeah just thought I'd mention this as a consideration for a future PR.

@louislefevre I am trying to implement the `locales` folder but do you know how to specify to node-RED that this is where the documentation is stored ?

**Comment by louislefevre** [comment]
> @louislefevre I am trying to implement the `locales` folder but do you know how to specify to node-RED that this is where the documentation is stored ?

https://nodered.org/docs/creating-nodes/i18n

*"The locales directory must be in the same directory as the node’s .js file."*

It seems that to make it work, the locales folder needs to be in the same location as the node. This would mean:
- Moving all files from all nodes into a single folder, which will be quite messy.
- Or creating a locales folder for each node.

I think the second option would be cleaner, but might be worth checking if there are other methods of importing HTML from one file into another. Alternatively, keeping the documentation in the nodes HTML is also an option. I'll leave it up to you to decide what's best and easiest for you, given that you'll be the main one managing the documentation side of things.

**Review by KhesimReid — APPROVED** [review]

**Pull request merged**
