### PR TITLE
Louis/install-script

### PR DESCRIPTION
**Pull request by louislefevre**
### Purpose
New script for installing the package dependencies, creating the Node-RED user directory, and then linking the package to Node-RED.

Running the `npm run setup` command will now install the package dependencies, install Node-RED, link the package to Node-RED, and initialise the Python virtual environment.

Getting the repository setup for new developers/users, going from nothing to a working setup, can be done using these simple commands:
- `git clone https://github.com/louislefevre/node-red-contrib-quantum.git`
- `cd node-red-contrib-quantum`
- `npm run setup`
- `npm start`

### Changes
- Added `link.sh` shell script (4816465233e349b5e804299e3a92f2b4f8dd98c9).
- Fixed an issue with running `setup.py` where the kernel would fail to locate the Python interpreter using the shebang (9ad5884074fe9123633ea78d8f1583f734d98fcb).
- Renamed `setup.py` and `setup.sh` to `pyvenv.py` and `pyvenv.sh` (1a1faf7576627edce766cb40fdc40e204493aabe)
-  The `npm run setup` command now consists of two steps: linking the package to Node-RED, and then creating the Python virtual environment (1a1faf7576627edce766cb40fdc40e204493aabe).

### New Requirements
- Running `npm run clean` will now remove the virtual environment AND unlink the package from Node-RED, so be conscious of that when using it.

### CODE REVIEW

**Review by ttoktassynov — COMMENTED** [review]
Louis, looks good to me, but I have tried to run it on my machine and it failed. I posted an issue about it #17

**Review by KhesimReid — APPROVED** [review]
Works fine. Great job, Louis!

**Comment by louislefevre** [comment]
> Louis, looks good to me, but I have tried to run it on my machine and it failed. I posted an issue about it #17

I wrote a reply on that issue thread - can you test out my suggestion and see if it fixes the issue?

**Review by ttoktassynov — APPROVED** [review]
Ignore my previous comment, I have managed to find a work around on setting python3 as default on to be able to correctly run your script. Now it looks good to me.

**Pull request merged**
