### PR TITLE
New structure according to the palette categories

### PR DESCRIPTION
**Pull request by Theo-Reignier**
### Purpose

New structure of the `node-red-contrib-quantum` repository according to the palette structure (2 categories of nodes).

```
> node-red-contrib-quantum
   > nodes
      > quantum
         > quantum-circuit
         > quantum-register
         ...
      > quantum-algorithms
         > grover
         > short
         ...
      errors.js
      python.js
      snippets.js
      state.js
``` 

### Changes

No changes were required except changing the paths in `package.json`.
If you ever think about some code that needs to be updated, please let me know !

### CODE REVIEW

**Comment by louislefevre** [comment]
The structure of the `test/` directory needs to be updated as well, and the `require` statements used in the tests need to be modified to reflect the new changes.

**Comment by louislefevre** [comment]
I've pushed some commits to update the paths for the unit tests, the npm package files listing in `package.json`, the workflow paths in `node.js.yml`, and the paths referenced in `CONTRIBUTING.md`. I think everything should be ready to merge now.

**Review by louislefevre — APPROVED** [review]

**Comment by Theo-Reignier** [comment]
> I've pushed some commits to update the paths for the unit tests, the npm package files listing in `package.json`, the workflow paths in `node.js.yml`, and the paths referenced in `CONTRIBUTING.md`. I think everything should be ready to merge now.

Thanks a lot Louis, I did not intend to give you more work, sorry about that.

**Comment by louislefevre** [comment]
> Thanks a lot Louis, I did not intend to give you more work, sorry about that.

Aha no problem, only took a few minutes 😁

**Review by KhesimReid — APPROVED** [review]

**Pull request merged**
